name: Build and push image

# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

on:
  schedule:
    # I don't think imaptest or dovecot change all that frequently, so once a
    # week should be sufficient
    - cron:  '30 5 * * 0'
  workflow_dispatch: {}

jobs:
  build_and_push:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/docker-login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Secrets managed at
          # https://github.com/jheiss/imaptest-docker/settings/secrets/actions
          # Password is an access token managed at
          # https://hub.docker.com/settings/security
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/marketplace/actions/docker-metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jheiss/imaptest
          flavor: |
            latest=true
          # type=ref for workflow_dispatch events, type=schedule for schedule events
          tags: |
            type=ref,event=branch
            type=schedule,pattern={{date 'YYYYMMDD'}}

      # https://github.com/marketplace/actions/build-and-push-docker-images      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          # https://docs.docker.com/build/ci/github-actions/multi-platform/
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
